project:
  type: website
  render:
    - /docs/**/*.md
    - index.md
    - 404.md
  output-dir: _site
  resources: 
    - "docs/**/*.mp4"
    - "assets/Notebooks/*.mp4"
    - "assets/files/*.pdf"
    - "assets/js/**"
    - "assets/files/*.csv"

format: 
  fminxyz-html: default
  # pdf:
  #   pdf-engine: xelatex
  #   number-sections: true
  #   number-depth: 1
  #   keep-tex: true
  gfm: default

format-links:
  - fminxyz-html
  - format: gfm
    text: Markdown
  # - format: pdf
    # text: PDF

execute:
  freeze: auto

filters:
  - fminxyz

website:
  site-url: https://fmin.xyz
  navbar:
    title: false
    logo: logo.svg
    logo-alt: fmin.xyz
    tools:
      - icon: github
        href: https://github.com/MerkulovDaniil/optim
      - icon: youtube
        href: https://www.youtube.com/@fmin
      - icon: telegram
        href: https://t.me/fminxyz
  sidebar: 
    style: "docked"
    collapse-level: 1
    contents: docs/**/*.md
  repo-url: https://github.com/MerkulovDaniil/optim
  repo-branch: master
  repo-actions: [edit]
  search: 
    location: navbar
    type: textbox
  twitter-card: true
  open-graph: true
  favicon: favicon.svg
  # reader-mode: true
  # back-to-top-navigation: true
  margin-footer: |
      <button type="button" name="button" class="btn" id="toggleSpoilers">🔽</button>